#!/usr/bin/env python3
"""Build four exact 2:1 isometric road-cell frames from a seamless AI texture.

The generated material provides appearance only. This script owns the grid
geometry: every frame is exactly 128x64 and its opaque region is the same
diamond as one World-122 block cell.
"""

import argparse
import math
from pathlib import Path

import numpy as np
from PIL import Image


FRAME_W = 128
FRAME_H = 64
SUPERSAMPLE = 4
PHASES = (
    (0.07, 0.11),
    (0.43, 0.19),
    (0.18, 0.57),
    (0.64, 0.68),
)


def bilinear_periodic(rgb, tx, ty):
    h, w = rgb.shape[:2]
    fx = np.mod(tx, 1.0) * w
    fy = np.mod(ty, 1.0) * h
    x0 = np.floor(fx).astype(np.int32) % w
    y0 = np.floor(fy).astype(np.int32) % h
    x1 = (x0 + 1) % w
    y1 = (y0 + 1) % h
    ax = (fx - np.floor(fx))[..., None]
    ay = (fy - np.floor(fy))[..., None]
    top = rgb[y0, x0] * (1.0 - ax) + rgb[y0, x1] * ax
    bottom = rgb[y1, x0] * (1.0 - ax) + rgb[y1, x1] * ax
    return top * (1.0 - ay) + bottom * ay


def make_frame(rgb, phase_x, phase_y):
    width = FRAME_W * SUPERSAMPLE
    height = FRAME_H * SUPERSAMPLE
    yy, xx = np.mgrid[0:height, 0:width]
    nx = (xx + 0.5 - width / 2) / (width / 2)
    ny = (yy + 0.5 - height / 2) / (height / 2)

    # Inverse isometric mapping from the exact 2:1 screen diamond to a square.
    tile_u = (nx + ny) * 0.5 + 0.5 + phase_x
    tile_v = (ny - nx) * 0.5 + 0.5 + phase_y
    inside = (np.abs(nx) + np.abs(ny)) <= 1.0

    sampled = bilinear_periodic(rgb, tile_u, tile_v)
    rgba = np.zeros((height, width, 4), dtype=np.uint8)
    rgba[..., :3] = np.clip(sampled, 0, 255).astype(np.uint8)
    rgba[..., 3] = inside.astype(np.uint8) * 255
    return Image.fromarray(rgba, "RGBA").resize(
        (FRAME_W, FRAME_H),
        Image.Resampling.LANCZOS,
    )


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("src", help="seamless road texture generated by floor-asset.py")
    parser.add_argument("dst", help="output 4-frame horizontal spritesheet")
    args = parser.parse_args()

    src = Image.open(args.src).convert("RGB")
    rgb = np.asarray(src, dtype=np.float32)
    frames = [make_frame(rgb, px, py) for px, py in PHASES]
    sheet = Image.new("RGBA", (FRAME_W * len(frames), FRAME_H))
    for index, frame in enumerate(frames):
        sheet.alpha_composite(frame, (index * FRAME_W, 0))

    dst = Path(args.dst)
    dst.parent.mkdir(parents=True, exist_ok=True)
    sheet.save(dst, optimize=True)

    alpha = np.asarray(sheet.getchannel("A"))
    coverage = float((alpha > 8).mean()) * 100.0
    print(
        f"{dst}: {sheet.size}, frames={len(frames)}, "
        f"frame={FRAME_W}x{FRAME_H}, alpha_coverage={coverage:.2f}%"
    )


if __name__ == "__main__":
    main()
