$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest
Add-Type -AssemblyName System.Drawing

# Deterministic size/anchor export only; glove artwork and transparency come from ImageGen.
$cursorRepo = [IO.Path]::GetFullPath((Join-Path $PSScriptRoot '../../..'))
$cursorManifest = Get-Content -LiteralPath (Join-Path $PSScriptRoot 'manifest.json') -Raw | ConvertFrom-Json
$cursorCss = [Collections.Generic.List[string]]::new()
$cursorCss.Add('/* Generated by tools/ai-gen/hand-cursors-cold-steel-20260830/export.ps1; do not edit. */')
$cursorCss.Add('/* Embedded PNGs keep cross-stylesheet and inline var() URLs independent of the consumer base path. */')
$cursorCss.Add(':root {')
foreach ($variant in $cursorManifest.variants) {
    $source = [Drawing.Bitmap]::new((Join-Path $PSScriptRoot $variant.source))
    $canvasSize = [int]$cursorManifest.canvasSize
    $output = [Drawing.Bitmap]::new($canvasSize, $canvasSize, [Drawing.Imaging.PixelFormat]::Format32bppArgb)
    $graphics = [Drawing.Graphics]::FromImage($output)
    try {
        $graphics.Clear([Drawing.Color]::Transparent)
        $graphics.CompositingMode = [Drawing.Drawing2D.CompositingMode]::SourceCopy
        $graphics.InterpolationMode = [Drawing.Drawing2D.InterpolationMode]::HighQualityBicubic
        $graphics.PixelOffsetMode = [Drawing.Drawing2D.PixelOffsetMode]::HighQuality
        # Bounds are the archived source's alpha>16 rectangle (x, y, width, height).
        # Fit the whole silhouette, not the palm, so the closed hand is not undersized.
        $bounds = $variant.sourceBounds
        $scale = $cursorManifest.visibleLongEdge / [double][Math]::Max($bounds[2], $bounds[3])
        $width = $bounds[2] * $scale
        $height = $bounds[3] * $scale
        $left = ($canvasSize - $width) / 2
        $top = ($canvasSize - $height) / 2
        $destination = [Drawing.RectangleF]::new(
            [single]$left, [single]$top, [single]$width, [single]$height)
        $sourceRectangle = [Drawing.RectangleF]::new($bounds[0], $bounds[1], $bounds[2], $bounds[3])
        $graphics.DrawImage($source, $destination, $sourceRectangle, [Drawing.GraphicsUnit]::Pixel)
        $assetPath = Join-Path $cursorRepo $variant.asset
        $output.Save($assetPath, [Drawing.Imaging.ImageFormat]::Png)
        $encoded = [Convert]::ToBase64String([IO.File]::ReadAllBytes($assetPath))
        # Reproject the fingertip/palm together with the image; actual pointer input is unchanged.
        $hotspotX = [int][Math]::Round($left + ($variant.sourceHotspot[0] - $bounds[0]) * $scale)
        $hotspotY = [int][Math]::Round($top + ($variant.sourceHotspot[1] - $bounds[1]) * $scale)
        $hotspot = @($hotspotX, $hotspotY) -join ' '
        $cursorCss.Add(('    --bp-cursor-{0}: url("data:image/png;base64,{1}") {2}, {0};' -f $variant.state, $encoded, $hotspot))
        Write-Output ('Exported {0}: {1}x{1}, visible long edge {2}px, hotspot {3}' -f $variant.asset, $canvasSize, $cursorManifest.visibleLongEdge, $hotspot)
    } finally {
        $graphics.Dispose()
        $output.Dispose()
        $source.Dispose()
    }
}
$cursorCss.Add('}')
[IO.File]::WriteAllText((Join-Path $cursorRepo $cursorManifest.cssOutput), ($cursorCss -join "`n") + "`n", [Text.UTF8Encoding]::new($false))
